# 1.生成器
生成器是一个特殊的函数,用于异步编程
异步编程 其他解决方案 使用纯回调函数
总感觉这个解决异步编程十分麻烦
``` javascript
  function* gen() {
    //yield 分隔符，将代码分成四块，迭代调用
    console.log("hello generator");
    yield "啥意思？";
    console.log(222);
    yield "什么用？";
    console.log(333);
    yield "函数代码的分隔符?";
    console.log(444);
  }
  let iterator = gen();
  console.log(iterator);
  // next()函数会运行到yield为止，yield相对与这个代码块的return
  iterator.next();
  iterator.next();
  //这里如果用上面的 iterator是输出空的，iterator已经到结尾了
  for (v of gen()) {
    console.log(v);
  }
```
## 生成器的函数参数
``` javascript
  function* gen(...arg) {
    console.log(arg);
    //第二next所传入的参数，会在第一次yield返回后，将yield作为下个代码块的参数。
    const yield1 = yield 111;
    console.log(yield1);
    yield 222;
    const yield4 = yield 333;
    console.log(yield4);
  }
  let iterator = gen("AAA");
  //那第一个next所传入的参数呢?
  console.log(iterator.next("ANAN"));
  //next 方法也是可以传入实参的
  console.log(iterator.next("BBB"));
  console.log(iterator.next());
  console.log(iterator.next("DDD"));
```
## 异步编程
1. 第一个生成器函数实例
``` javascript
function printByTime(delay) {
  setTimeout(() => {
    console.log(delay);
    iterator.next();
  }, delay);
}
function* gen() {
  yield printByTime(1000);
  yield printByTime(2000);
  yield printByTime(3000);
}
//这里需要用iterator接受，为了实现是在同一个迭代器运行
const iterator = gen();
iterator.next();
```
2. 第二个生成器函数实例
``` javascript 
function getUsers() {
  setTimeout(() => {
    let data = "用户数据";
    iterator.next(data);
  }, 1000);
}
function getOrders() {
  setTimeout(() => {
    let data = "订单数据";
    iterator.next(data);
  }, 1000);
}
function getGoods() {
  setTimeout(() => {
    let data = "商品数据";
    iterator.next(data);
  }, 1000);
}
function* gen() {
  let users = yield getUsers();
  console.log(users);
  let orders = yield getOrders();
  console.log(orders);
  let Goods = yield getGoods();
  console.log(Goods);
}
let iterator = gen();
iterator.next();
```
# promise
## promise的基本使用
``` javascript
//promise对象的三个状态 初始化 成功 失败
const p = new Promise(function (resolve, reject) {
  setTimeout(() => {
    // let data = "数据库中的用户数据";
    // resolve(data);

    let err = "读取用户数据失败";
    reject(err);
  }, 1000);
});
p.then(
  //当调用resolve时，状态为成功，就会去调用then里面的第一个回调函数
  (value) => {
    console.log(value);
  },
  //若是调用reject，状态为失败，会调用第二个回调函数
  (reason) => {
    //error 可以变红 真不错
    console.error(reason);
  }
);
```
### promise的读取文件案例
``` javascript
//1. 引入fs模块？
const fs = require('fs')

//2.调用方法读取文件
// fs.readFile('../笔记/ES6-11/1.ES6声明.md', (err, data) => {
//   if (err) throw err;
//   console.log(data.toString());
// })

//3.使用promise封装
const p = new Promise((resolve, reject) => {
  fs.readFile('../笔记/ES6-11/3.ES6异步编程.md', (err, data) => {
    if (err) reject(err)
    resolve(data)
  })
})
p.then(function (value) {
  console.log(value.toString());
},
  function (reason) {
    console.log('读取失败');
  })
```
## Promise的返回值
``` javascript
const p = new Promise((res, rej) => {
  setTimeout(() => {
    res("用户数据");
    rej("失败啦");
  }, 1000);
});
//调用then方法返回的还是Promise对象，这个对象的状态由回调函数的执行结果决定
const a = p.then(
  (res) => {
    //1. 如果回调函数返回的时 非promise类型的属性，状态为成功，返回值为对象的成功的值。
    console.log(res);
    return res;
    // 2.如果返回的是Promise对象的话，看返回的内部promiss对象是否成功，返回值为内部Promise返回的值.
    return new Promise((res, rej) => {
      rej("err");
    });
    //3.抛出错误,a的状态为失败，并且a的返回值为所throw抛出的内容
    throw "内部函数抛出的错误";
  },
  (err) => console.warn(err)
);
a.then((res) => {
  console.log(res);
}).catch((err) => {
  console.log(err);
});
console.log(a); //这里会先返回undefined，然后值会被修改为成功值
```
## Promise的链式调用
``` javascript
const p = new Promise((res, rej) => {
  setTimeout(() => {
    res("用户数据");
    rej("失败啦");
  }, 1000);
});
p.then((res) => {
  console.log(res);
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(res);
    }, 1000);
  });
})
  .then((res) => {
    console.log(res);
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(res);
      }, 1000);
    });
  })
  .then((res) => {
    console.log(res);
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(res);
      }, 1000);
    });
  });
```
### 链式调用的案例
``` javascript 
const fs = require('fs')  //这个需要用到node.js
new Promise((res) => {
  fs.readFile('../笔记/ES5/1.移动端.md', (err, data) => {
    res(data)
  })
}).then(res => {
  return new Promise(resolve => {
    fs.readFile('../笔记/ES5/2.本地存储.md', (err, data2) => {
      resolve(res + data2)
    })
  })
}).then(res => {
  return new Promise(resolve => {
    fs.readFile('../笔记/ES6-11/2.Symbol.md', (err, data3) => {
      resolve(res + data3)
    })
  })
}).then(res => {
  console.log(res);
}
)
```
## Promise.catch 
``` javascript
const p = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject("失败啦");
  }, 1000);
});
//其实和原先的then的第二个参数一样
p.catch((err) => {
  console.error(err);
});
```